### ISSUE TITLE
No "stop blinking" char

### ISSUE THREAD

**Issue by Khhs167** [shreder95ua/teasharp#3]
Once you run the command `del`, it returns `ACCESS DENIED` followed by blinking text, which i find funny, but there isnt any escape chars to then reset it back to normal after that, which is annoying to say the least!

**Comment by shreder95ua** [comment]
o hell no, i forgot to add an end char. ok, i let's go

**Comment by shreder95ua** [comment]
ok, everything done

**Comment by shreder95ua** [comment]
And also, `ACCESS DENIED` is a link to Half-Life 1.
