### ISSUE TITLE
Make interpreter store/interpret from file

### ISSUE THREAD

**Issue by mauro-balades** [shreder95ua/teasharp#6]

**Comment by shreder95ua** [comment]
what do you mean? like to load a file or import it? do you mean a `load` command? it all ready exists.

**Comment by mauro-balades** [comment]
no, do smth like `teasharp file.tsh` and `teasharp dump output.compiled_tsh`

**Comment by shreder95ua** [comment]
o no, binary((
unfortunately its not my level programming, sorry.

**Comment by mauro-balades** [comment]
No! I mean that... If u could interpret it from a file and not from input
