### ISSUE TITLE
Ignored spaces

### ISSUE THREAD

**Issue by shreder95ua** [shreder95ua/teasharp#9]
Sometimes space (` `) characters get ignored.
##### Example:
```
10 user = shreder95ua
20 Write Hello 
30 Write user
40 Write .
```
Returns `Helloshreder95ua.`

**Comment by varunpenumudi** [comment]
Hi i am varun. I know python and i think i can help you with this but i don't understand how your programming language works could you please explain me

**Comment by shreder95ua** [comment]
it's not really that complicated, but it's very different from all the other programming langs.

2. it splits spaces in your command (sorry, english is not mine main lang)
3. it checks the first command
4. it does what the command does.
#### an example:
`> Print Hello World!`
1. `print hello world!`
2. `["print","hello","world!"]`
3. `"print"`
4. `print(data)`

And the output is "Hello World!"

It's really fast, and on my 2006 pc, it works nice and dandy, even using windows CMD (unfortunately)

also: i probably know how to fix the error

**Comment by shreder95ua** [comment]
fixed!
